### PR TITLE
updated CoC for virtual event

### PR DESCRIPTION
**Pull request by reshamas**

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks! I have a PR in progress over at #157 (it's the `online` branch of this repo). Feel free to push to that branch to be rolled into the other website update work.

**Comment by jasongrout** [comment]
I think I pulled in your changes in #157 in https://github.com/jupytercon/jupytercon2020-website/pull/157/commits/32de2c698e0c852b4619072d9bd906747a5cea1a and https://github.com/jupytercon/jupytercon2020-website/pull/157/commits/55c4b59ca03bb0737faf0a7bf6674a35188b90c2. Are those the changes you were wanting to make?

**Comment by reshamas** [comment]
@jasongrout How do I see if my changes have been rendered in online version of website?

Also, as an aside, curious to know how to merge in specific commits for personal learning of Git/GH.

**Comment by jasongrout** [comment]
> @jasongrout How do I see if my changes have been rendered in online version of website?

There is a preview of the current state of #157 (or any other PR in this repo) by clicking on the "Deploy preview" CI test Details: 
Screen Shot 2020-06-17 at 7 13 59 AM

Right now, for #157, that leads to https://deploy-preview-157--suspicious-hugle-5d5ab5.netlify.app/, where you should see your CoC and diversity changes.

> Also, as an aside, curious to know how to merge in specific commits for personal learning of Git/GH.

I pulled the commits from your repo branch for #158 into my local git repo with something like:
```
git fetch https://github.com/reshamas/jupytercon2020-website.git community_sponsor
```
(this pulls in the commits into my repo without merging them into a branch, just so they're available)

Then I could "[cherry pick](https://git-scm.com/docs/git-cherry-pick)" the commits that looked like they were your changes, which were the two commits from #158: https://github.com/jupytercon/jupytercon2020-website/pull/158/commits
```
git cherry-pick e996f2f8680aabc876d836207d3839662f5c6665
git cherry-pick 65644e0a22fe7c4739dd81e0fd6a1bbf16dca7b1
```

**Comment by reshamas** [comment]
Thanks @jasongrout.
It looks like I still need to update some sentences.  Do I submit a PR just like before, but this time to the "online" branch?
Or maybe I should `fetch` the online branch once this PR has been merged in and submit any edits that way.

**Comment by jasongrout** [comment]
>  It looks like I still need to update some sentences. Do I submit a PR just like before, but this time to the "online" branch?
> Or maybe I should `fetch` the online branch once this PR has been merged in and submit any edits that way.

Sorry, I didn't see this comment. Did this get resolved, or is there still more to do?

**Pull request closed without merging**
