### PR TITLE
Update COVID-19 statement

### PR DESCRIPTION
**Pull request by jasongrout**
This notes that we are temporarily suspending ticket sales and the cfp.

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @labarba @SylvainCorlay

**Comment by jasongrout** [comment]
@SylvainCorlay or @labarba - do you want to approve this statement and merge this PR?

**Comment by SylvainCorlay** [comment]
I approve the changes. Leaving the PR open for a bit to give the occasion to Lorena to comment.

**Comment by jasongrout** [comment]
Merging since it has been approved. Thanks!

**Pull request merged**
