### PR TITLE
Diversity; move up PyLadies groups

### PR DESCRIPTION
**Pull request by reshamas**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
LGTM.

**Comment by reshamas** [comment]
@SylvainCorlay 
I don't see the changes from the PR reflected on the Diversity or Community Sponsors pages:
https://jupytercon.com/diversity/

Does it take a while to see the updated page?

**Comment by cmaureir** [comment]
I have no idea why the order was not altered, maybe there is a function that sorts them out?

**Comment by SylvainCorlay** [comment]
triggered a rebuild

**Pull request merged**
