### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by jasongrout**
Some grammar and punctuation fixes, as well as a better description for talks/posters and corrected prices for the Berlin Museum pass.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
> Corrected prices for the Berlin Museum pass

wow

**Comment by SylvainCorlay** [comment]
@jasongrout please use a fork for future PRs. It does not seem that the CI is properly set up for working with upstream directly!

**Comment by jasongrout** [comment]
Sorry. I thought I had set it up to use a fork, but apparently I messed that part up.

**Comment by jasongrout** [comment]
> Sorry. I thought I had set it up to use a fork, but apparently I messed that part up.

Yep, I messed up my git remotes. Sorry.

**Comment by SylvainCorlay** [comment]
np

**Pull request merged**
