### PR TITLE
Diversity

### PR DESCRIPTION
**Pull request by reshamas**
moved two new community sponsor logos to the correct folder

### CODE REVIEW

**Comment by reshamas** [comment]
@cmaureir @SylvainCorlay 
I have no idea why this PR is failing.  Any hints?

**Comment by cmaureir** [comment]
> @cmaureir @SylvainCorlay
> I have no idea why this PR is failing. Any hints?

strange, I restarted it.
The problem was while building nuxt.

**Comment by SylvainCorlay** [comment]
The issue is that it cannot find `py101.png`.

```
Module not found: Error: Can't resolve '~/assets/images/sponsors/py101.png'
```

**Comment by SylvainCorlay** [comment]
The files are not in the right directory.

**Comment by cmaureir** [comment]
Thanks! so we just need to move them @reshamas and it will be ready :)

**Comment by reshamas** [comment]
I looked at the netlify preview and it's working now.  Also looks like the groups have changed order, which I wanted.  Thanks!

**Comment by SylvainCorlay** [comment]
Thanks. I merges. Will deploy in a few minutes.

**Pull request merged**
