### PR TITLE
Add tutorials and talks cfps

### PR DESCRIPTION
**Pull request by SylvainCorlay**

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I just added a link from the participate page. Looking at what is missing on the index.

**Comment by martinRenou** [comment]
Yeah sorry I meant the participate page. Also there should be links in the menus.

**Comment by maartenbreddels** [comment]
I see this: 
image
I think this might help:
```
h1 {
line-height: 100%;
}
```

**Comment by SylvainCorlay** [comment]
> h1 {
> line-height: 100%;
> }

Yes, I tried restyling `h1`, but my CSS does not appear to be applied, probably because of the scoping.

**Pull request merged**
