### PR TITLE
fix typo in spain_ai twitter link

### PR DESCRIPTION
**Pull request by OriolAbril**

### CODE REVIEW

**Comment by jasongrout** [comment]
CC @reshamas for review

**Comment by reshamas** [comment]
@jasongrout Approved!
Thanks for fixing that typo.

**Comment by jasongrout** [comment]
@SylvainCorlay will be deploying recent changes soon, and this will go out with that deployment. Thanks!

**Comment by SylvainCorlay** [comment]
Just hit deploy.

**Pull request merged**
