### PR TITLE
fixed diversity email address

### PR DESCRIPTION
**Pull request by reshamas**

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks!

**Comment by cmaureir** [comment]
Do we handle the images internally with a different resolution? the PyLadies Hamburg one was huge.

**Comment by jasongrout** [comment]
It is a bit big, but we have much bigger images to take care of (sizes in KB):

```
jupytercon2020-website/assets/images% find . -type f -exec ls -lk {} \; | awk '{print $5, $9}' | sort -nr
5600209 ./bcc_photo_exterior_view_4708_x_2648_pixel_350_dpi.jpg
3946111 ./commitee/joshua.jpg
2327699 ./bg/venue.png
2218088 ./bg/about.png
2202755 ./bg/home.png
1557678 ./commitee/rosie.jpg
1082499 ./bg/participate.png
992846 ./commitee/safia.jpg
813612 ./flickr/jupyter-desk.jpg
727360 ./bcc_aerial_view.jpg
726245 ./speed-network.jpg
724899 ./sponsors/pyladies_hamburg.png
723526 ./commitee/lorena.jpg
691495 ./flickr/groups.jpg
597513 ./image-berlin.jpg
566164 ./flickr/poster-session.jpg
528234 ./commitee/tania.jpg
483446 ./participate.jpg
463348 ./venue-berlin-roads.jpg
403738 ./commitee/kirstie.jpg
385531 ./commitee/cristian.jpg
384883 ./commitee/sylvain.jpg
365440 ./commitee/paco.jpg
268212 ./main-about.jpg
267114 ./commitee/carol.jpg
257187 ./commitee/dinu.jpg
213284 ./diversity-group.jpg
212306 ./sponsors/wwcode_Final
193825 ./commitee/reshama.jpg
191503 ./flickr/people_smiling_sitting.jpg
184424 ./commitee/laura.jpg
140864 ./commitee/jeremy.jpg
112385 ./sponsors/pub.jpeg
66211 ./explain.jpg
60352 ./commitee/jim.png
58700 ./image-berlin.webp
51059 ./commitee/amanda.png
47762 ./numfocus-logo.jpg
38654 ./commitee/jason.jpg
34227 ./commitee/wolf.jpg
29492 ./sponsors/WIA-Secondary-RGB.png
27969 ./sponsors/pydata.png
26353 ./commitee/gerard.jpg
19455 ./sponsors/NumFocus.png
16338 ./commitee/jim.jpg
7994 ./temp/portrait.png
7327 ./sponsors/pyladies_berlin.jpg
```

**Comment by jasongrout** [comment]
> Do we handle the images internally with a different resolution? the PyLadies Hamburg one was huge.

Looks like the build process actually downsizes the images quite a bit.

**Pull request merged**
